- name: make sure /cvmfs exists
  file:
    path: /cvmfs
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: install cvmfs repo package
  yum:
    name: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
    state: present
  become: true

- name: install cvmfs package
  yum:
    name: cvmfs
    state: latest
    update_cache: yes
  become: true

- name: make sure user_allow_other is set in /etc/fuse.conf
  lineinfile:
    dest=/etc/fuse.conf
    line='user_allow_other'
    regexp='^user_allow_other'
    state=present
  become: true

- name: install /etc/cvmfs/default.local
  copy:
    src: ../files/default.local
    dest: /etc/cvmfs/default.local
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    force: yes
  become: true

- name: make sure /cvmfs/icecube.opensciencegrid.org exists
  file:
    path: /cvmfs/icecube.opensciencegrid.org
    state: directory
    owner: cvmfs
    group: cvmfs
    mode: 0755
  become: true

- name: make sure /cvmfs/icecube.opensciencegrid.org is in /etc/fstab and mounted
  mount:
    name: /cvmfs/icecube.opensciencegrid.org
    src: icecube.opensciencegrid.org
    fstype: cvmfs
    opts: defaults,_netdev,nodev
    state: mounted
  become: true
