- name: rebuild initrd
  command: /usr/bin/dracut -f
  become: true

- name: restart sshd
  service: 
    name=sshd
    state=restarted
  become: true

- name: reboot host
  command: /usr/bin/systemd-run --on-active=10 /usr/bin/systemctl reboot
  async: 0
  poll: 0
  listen: "reboot host and wait"
  become: true

- name: wait for host sshd
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=600 delay=60
  listen: "reboot host and wait"

- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  become: true
